updated 27

diff --git a/.github/workflows/build-ios-app.yml b/.github/workflows/build-ios-app.yml
--- a/.github/workflows/build-ios-app.yml
+++ b/.github/workflows/build-ios-app.yml
@@ -95,7 +95,99 @@
 #          # Add any other options as needed
 
 
-name: Build iOS application CICD
+
+
+
+
+
+#name: Build iOS application CICD
+#
+#on:
+#  push:
+#    paths:
+#      - .github/workflows/build-ios-app.yml
+#
+#jobs:
+#  build_with_signing:
+#    runs-on: macos-latest
+#    steps:
+#      - name: Check Xcode version
+#        run: |
+#          xcode_version=$(xcodebuild -version | grep "Xcode")
+#          if [[ "$xcode_version" =~ "Xcode 13" || "$xcode_version" =~ "Xcode 14" ]]; then
+#            echo "Xcode version is compatible: $xcode_version"
+#          else
+#            echo "Error: Xcode version $xcode_version is not supported. Please use Xcode 13 or above."
+#            exit 1
+#          fi
+#
+#      - name: Decode export options plist
+#        run: |
+#          echo "${{ secrets.EXPORT_OPTIONS_PLIST }}" | base64 --decode > export_options.plist
+#
+#      - name: Checkout repository
+#        uses: actions/checkout@v3
+#
+#      - name: Install CocoaPods dependencies
+#        run: |
+#          gem install cocoapods
+#          pod install
+#
+#      - name: Install Apple certificate and provisioning profile
+#        env:
+#          BUILD_CERTIFICATE_BASE64: ${{ secrets.BUILD_CERTIFICATE_BASE64 }}
+#          P12_PASSWORD: ${{ secrets.P12_PASSWORD }}
+#          BUILD_PROVISION_PROFILE_BASE64: ${{ secrets.BUILD_PROVISION_PROFILE_BASE64 }}
+#          KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
+#        run: |
+#          # Create variables
+#          CERTIFICATE_PATH=$RUNNER_TEMP/build_certificate.p12
+#          PP_PATH=$RUNNER_TEMP/build_pp.mobileprovision
+#          KEYCHAIN_PATH=$RUNNER_TEMP/app-signing.keychain-db
+#
+#          # Import certificate and provisioning profile from secrets
+#          echo -n "$BUILD_CERTIFICATE_BASE64" | base64 --decode -o $CERTIFICATE_PATH
+#          echo -n "$BUILD_PROVISION_PROFILE_BASE64" | base64 --decode -o $PP_PATH
+#
+#          # Create temporary keychain
+#          security create-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
+#          security set-keychain-settings -lut 21600 $KEYCHAIN_PATH
+#          security unlock-keychain -p "$KEYCHAIN_PASSWORD" $KEYCHAIN_PATH
+#
+#          # Import certificate to keychain
+#          security import $CERTIFICATE_PATH -P "$P12_PASSWORD" -A -t cert -f pkcs12 -k $KEYCHAIN_PATH
+#          security list-keychain -d user -s $KEYCHAIN_PATH
+#
+#          # Apply provisioning profile
+#          mkdir -p ~/Library/MobileDevice/Provisioning\ Profiles
+#          cp $PP_PATH ~/Library/MobileDevice/Provisioning\ Profiles
+#
+#      - name: Generate and archive
+#        run: |
+#          xcodebuild -workspace "CICDDemoApp.xcworkspace" \
+#          -scheme "CICDDemoApp" \
+#          -configuration Debug \
+#          -archivePath $RUNNER_TEMP/CICDDemoApp.xcarchive \
+#          clean archive \
+#          -allowProvisioningUpdates
+#
+#          # Export IPA
+#          xcodebuild -exportArchive -archivePath $RUNNER_TEMP/CICDDemoApp.xcarchive \
+#          -exportOptionsPlist $RUNNER_TEMP/ExportOptions.plist \
+#          -exportPath $RUNNER_TEMP/build
+#
+#          # Move IPA to workspace
+#          mv $RUNNER_TEMP/build/CICDDemoApp.ipa $GITHUB_WORKSPACE
+#
+#      - name: Upload IPA as artifact
+#        uses: actions/upload-artifact@v2
+#        with:
+#          name: CICDDemoApp
+#          path: $GITHUB_WORKSPACE/CICDDemoApp.ipa
+
+
+
+name: Build iOS application
 
 on:
   push:
@@ -118,7 +210,7 @@ jobs:
 
       - name: Decode export options plist
         run: |
-          echo "${{ secrets.EXPORT_OPTIONS_PLIST }}" | base64 --decode > export_options.plist
+          cp /Users/sayalitembhurne/Documents/CICDDemoApp/CICDDemoApp/ExportOptions.plist $RUNNER_TEMP/export_options.plist
 
       - name: Checkout repository
         uses: actions/checkout@v3
@@ -168,7 +260,7 @@ jobs:
 
           # Export IPA
           xcodebuild -exportArchive -archivePath $RUNNER_TEMP/CICDDemoApp.xcarchive \
-          -exportOptionsPlist $RUNNER_TEMP/ExportOptions.plist \
+          -exportOptionsPlist $RUNNER_TEMP/export_options.plist \
           -exportPath $RUNNER_TEMP/build
 
           # Move IPA to workspace
